# Generated by Django 3.1.2 on 2020-11-14 00:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 14, 0, 4, 46, 421138, tzinfo=utc), verbose_name='Fecha de Publicación'),
        ),
    ]
